pragma Singleton

import QtQuick
import Quickshell

// Caelestia i18n-Singleton (Fork galdo/shell, Branch de-i18n).
// Quickshell hat keine QTranslator-Unterstuetzung -> eigenes String-Mapping.
// t("...") liefert die deutsche Uebersetzung, wenn System-Locale = de UND ein
// Eintrag existiert; sonst den Originalstring (Passthrough -> nie leere UI).
// Platzhalter (%1 etc.) bleiben erhalten: t("Now using: %1").arg(x) funktioniert.
Singleton {
    id: root

    readonly property bool german: Qt.locale().name.startsWith("de")

    function t(s) {
        if (german && root.de[s] !== undefined)
            return root.de[s];
        return s;
    }

    // Deutsche Uebersetzungen. Schluessel = Originalstring (exakt wie im qsTr()).
    // Reine Formatstrings/Symbole (z. B. "%1%", "+%1", "—", "%1 MHz") sind bewusst
    // NICHT enthalten -> Passthrough.
    readonly property var de: ({
        "1 app playing audio": "1 App gibt Audio wieder",
        "%1 apps playing audio": "%1 Apps geben Audio wieder",
        " (%1 connected)": " (%1 verbunden)",
        "%1 device%2 available": "%1 Gerät%2 verfügbar",
        "%1 devices available": "%1 Geräte verfügbar",
        "%1 networks available": "%1 Netzwerke verfügbar",
        "%1 notification%2": "%1 Benachrichtigung%2",
        "%1 on monitor %2 at %3, %4": "%1 auf Monitor %2 bei %3, %4",
        "7-Day Forecast": "7-Tage-Vorhersage",
        "About": "Über",
        "Actions": "Aktionen",
        "Active indicator": "Aktiver Indikator",
        "Actively probe for a network that doesn't broadcast its name": "Aktiv nach einem Netzwerk suchen, das seinen Namen nicht sendet",
        "Active since %1": "Aktiv seit %1",
        "Active trail": "Aktive Spur",
        "Active window": "Aktives Fenster",
        "Add": "Hinzufügen",
        "Add network": "Netzwerk hinzufügen",
        "Add provider": "Anbieter hinzufügen",
        "Address": "Adresse",
        "Address: %1": "Adresse: %1",
        "Address (CIDR)": "Adresse (CIDR)",
        "Add VPN provider": "VPN-Anbieter hinzufügen",
        "Adjust the volume of individual apps currently playing audio.": "Lautstärke einzelner Apps anpassen, die gerade Audio wiedergeben.",
        "A high chroma palette. The primary palette's chroma is at maximum.": "Eine Palette mit hoher Sättigung. Die Sättigung der Primärpalette ist maximal.",
        "All apps": "Alle Apps",
        "All colours are grayscale, no chroma.": "Alle Farben sind Graustufen, keine Sättigung.",
        "All networks": "Alle Netzwerke",
        "Allow actions that shut down or log out": "Aktionen erlauben, die herunterfahren oder abmelden",
        "Allow nearby devices to find this one": "Geräten in der Nähe erlauben, dieses zu finden",
        "Allow nearby devices to pair with this one": "Geräten in der Nähe erlauben, sich mit diesem zu koppeln",
        "Allow this device to connect automatically": "Diesem Gerät erlauben, sich automatisch zu verbinden",
        "Allow this device to wake the system": "Diesem Gerät erlauben, das System aufzuwecken",
        "All up to date!": "Alles aktuell!",
        "Almost identical to fidelity.": "Fast identisch mit Fidelity.",
        "Always visible": "Immer sichtbar",
        "A medium chroma palette. The primary palette's hue is different from the seed colour, for variety.": "Eine Palette mit mittlerer Sättigung. Der Farbton der Primärpalette weicht zur Abwechslung von der Startfarbe ab.",
        "Amount the brightness changes per scroll (%)": "Helligkeitsänderung pro Scrollschritt (%)",
        "Amount the volume changes per scroll (%)": "Lautstärkeänderung pro Scrollschritt (%)",
        "An error occurred": "Ein Fehler ist aufgetreten",
        "A playful theme - the seed colour's hue does not appear in the theme.": "Ein verspieltes Thema – der Farbton der Startfarbe erscheint nicht im Thema.",
        "App ID": "App-ID",
        "App info": "App-Info",
        "Apply": "Anwenden",
        "Apps": "Apps",
        "App volumes": "App-Lautstärken",
        "App volumes, sound devices": "App-Lautstärken, Audiogeräte",
        "Audio": "Audio",
        "Audio input changed": "Audioeingang geändert",
        "Audio input changes": "Änderungen des Audioeingangs",
        "Audio output changed": "Audioausgang geändert",
        "Audio output changes": "Änderungen des Audioausgangs",
        "Authentication required": "Authentifizierung erforderlich",
        "Auto": "Auto",
        "Automatic (DHCP)": "Automatisch (DHCP)",
        "Automatic, DNS only": "Automatisch, nur DNS",
        "Available devices": "Verfügbare Geräte",
        "Back": "Zurück",
        "Backend: %1": "Backend: %1",
        "Background": "Hintergrund",
        "Base %1, layers %2": "Basis %1, Ebenen %2",
        "Battery": "Akku",
        "Battery is charging": "Akku wird geladen",
        "Battery is discharging": "Akku entlädt sich",
        "Battery level is low": "Akkustand ist niedrig",
        "Battery warning": "Akku-Warnung",
        "Behaviour": "Verhalten",
        "Blocked": "Blockiert",
        "Bluetooth": "Bluetooth",
        "Bluetooth disabled": "Bluetooth deaktiviert",
        "Bluetooth, pairing": "Bluetooth, Kopplung",
        "Brightness": "Helligkeit",
        "Brightness step": "Helligkeitsschritt",
        "Browse": "Durchsuchen",
        "Browse installed apps, set favourites and hidden": "Installierte Apps durchsuchen, Favoriten und Ausgeblendete festlegen",
        "Built-in id or a custom name": "Integrierte ID oder ein eigener Name",
        "Built-in names (wireguard, warp, tailscale, netbird) auto-fill their commands. For others, provide the connect/disconnect commands.": "Integrierte Namen (wireguard, warp, tailscale, netbird) füllen ihre Befehle automatisch aus. Für andere die Verbinden-/Trennen-Befehle angeben.",
        "Calculating...": "Berechne...",
        "Cancel": "Abbrechen",
        "Caps lock": "Feststelltaste",
        "Capslock: %1": "Feststelltaste: %1",
        "Caps lock and Num lock are ON.": "Feststelltaste und Num-Taste sind AN.",
        "Caps lock and Num lock are ON.\\nKeyboard layout: %1": "Feststelltaste und Num-Taste sind AN.\\nTastaturlayout: %1",
        "Caps lock changes": "Änderungen der Feststelltaste",
        "Caps lock disabled": "Feststelltaste deaktiviert",
        "Caps lock enabled": "Feststelltaste aktiviert",
        "Caps lock is currently disabled": "Feststelltaste ist derzeit deaktiviert",
        "Caps lock is currently enabled": "Feststelltaste ist derzeit aktiviert",
        "Caps lock is ON.": "Feststelltaste ist AN.",
        "Caps lock is ON. Kb layout: %1": "Feststelltaste ist AN. Layout: %1",
        "Cards": "Karten",
        "Charger plugged in": "Ladegerät angeschlossen",
        "Charger unplugged": "Ladegerät getrennt",
        "Charging": "Lädt",
        "Charging changes": "Änderungen des Ladezustands",
        "Choose your weather location on a map in a future update": "Wetterort auf einer Karte wählen (in einem künftigen Update)",
        "CLI": "CLI",
        "Clock": "Uhr",
        "Clock format": "Uhrzeitformat",
        "Close to grayscale, a hint of chroma.": "Nahe an Graustufen, ein Hauch von Sättigung.",
        "Collecting data...": "Sammle Daten...",
        "Colours": "Farben",
        "Command": "Befehl",
        "Comma-separated": "Kommagetrennt",
        "Compact": "Kompakt",
        "Components": "Komponenten",
        "Config loaded": "Konfiguration geladen",
        "Config loaded successfully!": "Konfiguration erfolgreich geladen!",
        "Connect": "Verbinden",
        "Connect automatically": "Automatisch verbinden",
        "Connect command": "Verbinden-Befehl",
        " • Connected": " • Verbunden",
        "Connected": "Verbunden",
        "Connected • %1": "Verbunden • %1",
        "Connected%1": "Verbunden%1",
        "Connected devices": "Verbundene Geräte",
        "Connected to %1": "Verbunden mit %1",
        "Connecting...": "Verbinde...",
        "Connection": "Verbindung",
        "Connection failed — check the password": "Verbindung fehlgeschlagen — Passwort prüfen",
        "Connection failed. Please check your password and try again.": "Verbindung fehlgeschlagen. Bitte Passwort prüfen und erneut versuchen.",
        "Connect or disconnect the VPN": "VPN verbinden oder trennen",
        "Content": "Inhalt",
        "Could not connect to %1": "Verbindung zu %1 nicht möglich",
        "Could not start %1. Is it installed?": "%1 konnte nicht gestartet werden. Ist es installiert?",
        "CPU": "CPU",
        "CPU, memory and GPU update interval (seconds)": "Aktualisierungsintervall für CPU, Speicher und GPU (Sekunden)",
        "Current Ping": "Aktueller Ping",
        "Custom commands (optional)": "Eigene Befehle (optional)",
        "Dark theme": "Dunkles Thema",
        "Dashboard": "Dashboard",
        "Dashboard, taskbar, launcher, sidebar": "Dashboard, Taskleiste, Launcher, Seitenleiste",
        "Data usage: %1": "Datenverbrauch: %1",
        "Date, icon, background": "Datum, Symbol, Hintergrund",
        "Default applications": "Standardanwendungen",
        "Default apps, favourites, hidden apps": "Standard-Apps, Favoriten, ausgeblendete Apps",
        "Default for Material theme colours. A pastel palette with a low chroma.": "Standard für Material-Themenfarben. Eine Pastellpalette mit geringer Sättigung.",
        "Default player": "Standard-Player",
        "Default timeout": "Standard-Zeitüberschreitung",
        "Delete": "Löschen",
        "Delete recording?": "Aufnahme löschen?",
        "Derive theme mode and variant from the wallpaper": "Themenmodus und -variante aus dem Hintergrundbild ableiten",
        "Desktop": "Desktop",
        "Details": "Details",
        "Device": "Gerät",
        "Disabled": "Deaktiviert",
        "Disabled Hyprland animations, blur, gaps and shadows": "Hyprland-Animationen, Weichzeichner, Abstände und Schatten deaktiviert",
        "Disconnect": "Trennen",
        "Disconnect command": "Trennen-Befehl",
        "Disconnected from %1": "Von %1 getrennt",
        "Disconnecting...": "Trenne...",
        "Discoverable": "Sichtbar",
        "Discovering": "Suche läuft",
        "Dismiss notifications after their timeout": "Benachrichtigungen nach Ablauf ausblenden",
        "Display": "Anzeige",
        "Display name": "Anzeigename",
        "Display wallpaper": "Hintergrundbild anzeigen",
        "Distro": "Distribution",
        "DNS servers": "DNS-Server",
        "Do not disturb": "Nicht stören",
        "Do not disturb changes": "Änderungen von „Nicht stören“",
        "Do not disturb disabled": "„Nicht stören“ deaktiviert",
        "Do not disturb enabled": "„Nicht stören“ aktiviert",
        "Download": "Herunterladen",
        "Drag threshold": "Ziehschwelle",
        "Edit VPN provider": "VPN-Anbieter bearbeiten",
        "e.g. MyHiddenNetwork": "z. B. MeinVerstecktesNetzwerk",
        "Enabled": "Aktiviert",
        "Enable dangerous actions": "Gefährliche Aktionen aktivieren",
        "Enable widgets in the dashboard settings": "Widgets in den Dashboard-Einstellungen aktivieren",
        "Enhanced Open": "Enhanced Open",
        "Enter a valid address in CIDR notation": "Gültige Adresse in CIDR-Notation eingeben",
        "Enter a valid gateway address": "Gültige Gateway-Adresse eingeben",
        "Enter password": "Passwort eingeben",
        "Enterprise": "Enterprise",
        "Enter the details below to manually connect to a network.": "Details unten eingeben, um sich manuell mit einem Netzwerk zu verbinden.",
        "Enter valid DNS server addresses": "Gültige DNS-Server-Adressen eingeben",
        "Enter your password": "Passwort eingeben",
        "Ethernet": "Ethernet",
        "Expire automatically": "Automatisch ablaufen",
        "Expressive": "Expressiv",
        "Face not recognized (%1/%2). Please try again.": "Gesicht nicht erkannt (%1/%2). Bitte erneut versuchen.",
        "Face not recognized (%1/%2). Please try again or use password.": "Gesicht nicht erkannt (%1/%2). Bitte erneut versuchen oder Passwort verwenden.",
        "Failed to parse config%1": "Konfiguration konnte nicht gelesen werden%1",
        "Failed to parse token config%1": "Token-Konfiguration konnte nicht gelesen werden%1",
        "Failed to save config%1": "Konfiguration konnte nicht gespeichert werden%1",
        "Favourite": "Favorit",
        "Featured wallpaper": "Vorgestelltes Hintergrundbild",
        "Feels like %1": "Gefühlt %1",
        "Fidelity": "Fidelity",
        "File manager": "Dateimanager",
        "Files": "Dateien",
        "Filter:": "Filter:",
        "Filters": "Filter",
        "Fingerprint not recognized (%1/%2). Please try again.": "Fingerabdruck nicht erkannt (%1/%2). Bitte erneut versuchen.",
        "Fingerprint not recognized (%1/%2). Please try again or use password.": "Fingerabdruck nicht erkannt (%1/%2). Bitte erneut versuchen oder Passwort verwenden.",
        "Firmware": "Firmware",
        "Float": "Schwebend",
        "Floating: %1": "Schwebend: %1",
        "Follows your system locale (%1)": "Folgt deinem System-Locale (%1)",
        "Forget": "Vergessen",
        "Frequency": "Frequenz",
        "Fruit Salad": "Fruit Salad",
        "Full": "Voll",
        "Fullscreen": "Vollbild",
        "Fullscreen state: %1": "Vollbildstatus: %1",
        "Fullscreen state: unknown": "Vollbildstatus: unbekannt",
        "Fuzzy search": "Unscharfe Suche",
        "Game mode": "Spielmodus",
        "Game mode changes": "Änderungen des Spielmodus",
        "Game mode disabled": "Spielmodus deaktiviert",
        "Game mode enabled": "Spielmodus aktiviert",
        "Gateway": "Gateway",
        "General": "Allgemein",
        "Generic": "Generisch",
        "GPU": "GPU",
        "Group preview count": "Anzahl Gruppenvorschauen",
        "Hibernating in 5 seconds": "Ruhezustand in 5 Sekunden",
        "Hibernating to prevent data loss": "Ruhezustand zur Vermeidung von Datenverlust",
        "Hidden": "Ausgeblendet",
        "Hidden network": "Verstecktes Netzwerk",
        "Hide from the launcher": "Im Launcher ausblenden",
        "High %1 • Low %2": "Hoch %1 • Tief %2",
        "Hostname": "Hostname",
        "Hourly forecast": "Stündliche Vorhersage",
        "How often available networks are rescanned (seconds)": "Wie oft verfügbare Netzwerke neu gescannt werden (Sekunden)",
        "How often the media position updates (ms)": "Wie oft die Medienposition aktualisiert wird (ms)",
        "How times are shown across the shell": "Wie Uhrzeiten in der Shell dargestellt werden",
        "Hyprland settings restored": "Hyprland-Einstellungen wiederhergestellt",
        "Image files": "Bilddateien",
        "Important": "Wichtig",
        "Incorrect password. Please try again.": "Falsches Passwort. Bitte erneut versuchen.",
        "Incorrect password. Please try again or use face.": "Falsches Passwort. Bitte erneut versuchen oder Gesicht verwenden.",
        "Incorrect password. Please try again or use fingerprint.": "Falsches Passwort. Bitte erneut versuchen oder Fingerabdruck verwenden.",
        "Indicators, window icons": "Indikatoren, Fenstersymbole",
        "Initial class: %1": "Anfangsklasse: %1",
        "Initial title: %1": "Anfangstitel: %1",
        "Input": "Eingang",
        "Input device": "Eingabegerät",
        "Input increments": "Eingabeschritte",
        "Interface": "Schnittstelle",
        "Inverted": "Invertiert",
        "IP address": "IP-Adresse",
        "IP and prefix, e.g. 192.168.1.50/24": "IP und Präfix, z. B. 192.168.1.50/24",
        "IP assignment": "IP-Zuweisung",
        "IPv4": "IPv4",
        "Join this network when it's in range": "Diesem Netzwerk beitreten, wenn es in Reichweite ist",
        "Keep awake": "Wach halten",
        "Keep Awake": "Wach halten",
        "Keep the bar visible at all times": "Leiste dauerhaft sichtbar halten",
        "Kernel": "Kernel",
        "Keyboard layout": "Tastaturlayout",
        "Keyboard layout: %1": "Tastaturlayout: %1",
        "Keyboard layout changed": "Tastaturlayout geändert",
        "Keyboard layout changes": "Änderungen des Tastaturlayouts",
        "Keyboard layout limit": "Tastaturlayout-Limit",
        "Keyboard Layouts": "Tastaturlayouts",
        "Kill": "Beenden",
        "Language": "Sprache",
        "Language & region": "Sprache & Region",
        "Launcher": "Launcher",
        "Layout changed to: %1": "Layout geändert zu: %1",
        "Leave empty to use the built-in default": "Leer lassen, um den integrierten Standard zu verwenden",
        "Library": "Bibliothek",
        "Loaded plugins": "Geladene Plugins",
        "Loading...": "Lädt...",
        "Loading lyrics...": "Lade Liedtext...",
        "Local IP Address": "Lokale IP-Adresse",
        "Local wallpapers": "Lokale Hintergrundbilder",
        "Location picker coming soon": "Ortsauswahl kommt bald",
        "Lyrics": "Liedtext",
        "Lyrics backend": "Liedtext-Backend",
        "MAC address": "MAC-Adresse",
        "Manage plugins": "Plugins verwalten",
        "Manual": "Manuell",
        "Matched by a regex in favouriteApps — edit the config file to change": "Durch einen Regex in favouriteApps erkannt — zum Ändern die Konfigurationsdatei bearbeiten",
        "Matched by a regex in hiddenApps — edit the config file to change": "Durch einen Regex in hiddenApps erkannt — zum Ändern die Konfigurationsdatei bearbeiten",
        "Matches the seed colour, even if the seed colour is very bright (high chroma).": "Entspricht der Startfarbe, auch wenn diese sehr hell ist (hohe Sättigung).",
        "Maximum attempts for all authentication methods reached.": "Maximale Anzahl an Versuchen für alle Authentifizierungsmethoden erreicht.",
        "Maximum face attempts reached. Please use password.": "Maximale Anzahl an Gesichtsversuchen erreicht. Bitte Passwort verwenden.",
        "Maximum fingerprint attempts reached. Please use password.": "Maximale Anzahl an Fingerabdruckversuchen erreicht. Bitte Passwort verwenden.",
        "Maximum number of toasts shown at once": "Maximale Anzahl gleichzeitig angezeigter Toasts",
        "Maximum password attempts reached.": "Maximale Anzahl an Passwortversuchen erreicht.",
        "Maximum password attempts reached. Please use face.": "Maximale Anzahl an Passwortversuchen erreicht. Bitte Gesicht verwenden.",
        "Maximum password attempts reached. Please use fingerprint.": "Maximale Anzahl an Passwortversuchen erreicht. Bitte Fingerabdruck verwenden.",
        "Max items shown": "Max. angezeigte Einträge",
        "Max tries reached": "Max. Versuche erreicht",
        "Max volume": "Max. Lautstärke",
        "Max wallpapers": "Max. Hintergrundbilder",
        "Max window icons": "Max. Fenstersymbole",
        "Media": "Medien",
        "Media & lyrics": "Medien & Liedtext",
        "Media playback": "Medienwiedergabe",
        "Media refresh": "Medien-Aktualisierung",
        "Memory": "Speicher",
        "Microphone": "Mikrofon",
        "Monitor: %1 (%2) at %3, %4": "Monitor: %1 (%2) bei %3, %4",
        "Monitoring: %1": "Überwache: %1",
        "Monitor: unknown": "Monitor: unbekannt",
        "Monochrome": "Monochrom",
        "Move to workspace": "Auf Arbeitsfläche verschieben",
        "Muted": "Stumm",
        "Mute or unmute the default source": "Standardquelle stummschalten oder Stummschaltung aufheben",
        "Navigate results with Ctrl+hjkl": "Ergebnisse mit Strg+hjkl navigieren",
        "Network": "Netzwerk",
        "Network: %1": "Netzwerk: %1",
        "Network interface (for WireGuard / status checks)": "Netzwerkschnittstelle (für WireGuard / Statusprüfungen)",
        "Network name is required": "Netzwerkname ist erforderlich",
        "Network name (SSID)": "Netzwerkname (SSID)",
        "Network: Unknown": "Netzwerk: Unbekannt",
        "Neutral": "Neutral",
        "Nexus — %1": "Nexus — %1",
        "No active client": "Kein aktiver Client",
        "No apps playing audio": "Keine Apps geben Audio wieder",
        "No battery detected": "Kein Akku erkannt",
        "No body here! :/": "Kein Inhalt hier! :/",
        "No description": "Keine Beschreibung",
        "No disks": "Keine Datenträger",
        "No disks detected": "Keine Datenträger erkannt",
        "No input devices": "Keine Eingabegeräte",
        "No local wallpapers found": "Keine lokalen Hintergrundbilder gefunden",
        "No lyrics found": "Kein Liedtext gefunden",
        "No media": "Keine Medien",
        "None": "Keine",
        "None (open)": "Keine (offen)",
        "No networks found": "Keine Netzwerke gefunden",
        "No Notifications": "Keine Benachrichtigungen",
        "No output devices": "Keine Ausgabegeräte",
        "No players": "Keine Player",
        "No recordings found": "Keine Aufnahmen gefunden",
        "No results": "Keine Ergebnisse",
        "Normal power management": "Normale Energieverwaltung",
        "No saved devices": "Keine gespeicherten Geräte",
        "No saved networks": "Keine gespeicherten Netzwerke",
        "Not connected": "Nicht verbunden",
        "Not connected • %1": "Nicht verbunden • %1",
        "Nothing playing": "Nichts wird wiedergegeben",
        "Notifications": "Benachrichtigungen",
        "Notifications shown per group before collapsing": "Pro Gruppe angezeigte Benachrichtigungen vor dem Einklappen",
        "Notifications, toasts, timeouts": "Benachrichtigungen, Toasts, Zeitüberschreitungen",
        "Not paired": "Nicht gekoppelt",
        "No VPN providers configured": "Keine VPN-Anbieter konfiguriert",
        "now": "jetzt",
        "Now": "Jetzt",
        "No wallpapers found": "Keine Hintergrundbilder gefunden",
        "No weather": "Kein Wetter",
        "No widgets enabled": "Keine Widgets aktiviert",
        "Now playing": "Wird wiedergegeben",
        "Now Playing": "Wird wiedergegeben",
        "Now using: %1": "Verwendet jetzt: %1",
        "Number of bars in the audio visualisers": "Anzahl der Balken in den Audio-Visualisierungen",
        "Number of workspaces displayed": "Anzahl der angezeigten Arbeitsflächen",
        "Num lock changes": "Änderungen der Num-Taste",
        "Num lock disabled": "Num-Taste deaktiviert",
        "Num lock enabled": "Num-Taste aktiviert",
        "Num lock is currently disabled": "Num-Taste ist derzeit deaktiviert",
        "Num lock is currently enabled": "Num-Taste ist derzeit aktiviert",
        "Num lock is ON.": "Num-Taste ist AN.",
        "Num lock is ON. Kb layout: %1": "Num-Taste ist AN. Layout: %1",
        "Occupied background": "Belegter Hintergrund",
        "Off": "Aus",
        "Offset: %1 ms": "Versatz: %1 ms",
        "On": "An",
        "Only show the active window title while hovering": "Aktiven Fenstertitel nur beim Überfahren anzeigen",
        "Open": "Öffnen",
        "Open expanded": "Erweitert öffnen",
        "Open in calculator": "Im Rechner öffnen",
        "Open settings": "Einstellungen öffnen",
        "Open the settings window": "Einstellungsfenster öffnen",
        "Output": "Ausgang",
        "Output configuration": "Ausgabekonfiguration",
        "Output device": "Ausgabegerät",
        "Override for GPU type": "Überschreibung für GPU-Typ",
        "Page under construction": "Seite im Aufbau",
        "Pairable": "Koppelbar",
        "Paired": "Gekoppelt",
        "Pairing...": "Koppeln...",
        "Pair new device": "Neues Gerät koppeln",
        "Panels": "Panels",
        "Password": "Passwort",
        "Password must be at least 8 characters": "Passwort muss mindestens 8 Zeichen lang sein",
        "Paused": "Pausiert",
        "Performance": "Leistung",
        "Performance Degraded": "Leistung reduziert",
        "Performance widgets": "Leistungs-Widgets",
        "Per-monitor workspaces": "Arbeitsflächen pro Monitor",
        "Persistent": "Dauerhaft",
        "Pin": "Anheften",
        "Pinned: %1": "Angeheftet: %1",
        "Pin to the top of the launcher": "Oben im Launcher anheften",
        "Pixels dragged before the bar reveals": "Gezogene Pixel, bevor die Leiste erscheint",
        "Pixels dragged before the dashboard opens": "Gezogene Pixel, bevor das Dashboard öffnet",
        "Pixels dragged before the launcher opens": "Gezogene Pixel, bevor der Launcher öffnet",
        "Pixels dragged before the sidebar opens": "Gezogene Pixel, bevor die Seitenleiste öffnet",
        "Play something for it to show up here!": "Spiele etwas ab, damit es hier erscheint!",
        "Plugins": "Plugins",
        "Polling": "Abfrage",
        "Poll intervals, lyrics backend": "Abfrageintervalle, Liedtext-Backend",
        "Popout on hover": "Beim Überfahren ausklappen",
        "Popup notifications are now disabled": "Popup-Benachrichtigungen sind jetzt deaktiviert",
        "Popup notifications are now enabled": "Popup-Benachrichtigungen sind jetzt aktiviert",
        "Position: %1, %2": "Position: %1, %2",
        "Power profile: %1": "Energieprofil: %1",
        "Preferred media player when several are open": "Bevorzugter Media-Player, wenn mehrere geöffnet sind",
        "Preventing sleep mode": "Verhindert den Ruhemodus",
        "Prevent this device from connecting": "Dieses Gerät am Verbinden hindern",
        "Primary DNS": "Primärer DNS",
        "Process id: %1": "Prozess-ID: %1",
        "Provider name": "Anbietername",
        "Provider name is required": "Anbietername ist erforderlich",
        "Qt": "Qt",
        "Quickshell": "Quickshell",
        "Quick toggles": "Schnellschalter",
        "Quick Toggles": "Schnellschalter",
        "Rainbow": "Regenbogen",
        "Random": "Zufällig",
        "Ready": "Bereit",
        "Reason: %1": "Grund: %1",
        "Recolour icons": "Symbole umfärben",
        "Record fullscreen": "Vollbild aufnehmen",
        "Record fullscreen with sound": "Vollbild mit Ton aufnehmen",
        "Recording '%1' will be permanently deleted.": "Aufnahme „%1“ wird endgültig gelöscht.",
        "Recording at %1": "Aufnahme bei %1",
        "Recording for %1": "Aufnahme seit %1",
        "Recordings": "Aufnahmen",
        "Record region": "Bereich aufnehmen",
        "Record region with sound": "Bereich mit Ton aufnehmen",
        "Region": "Region",
        "Remaining: %1%": "Verbleibend: %1%",
        "Rescan networks": "Netzwerke neu scannen",
        "Reveal on drag": "Beim Ziehen einblenden",
        "Reveal on hover": "Beim Überfahren einblenden",
        "Reveal the bar when the cursor reaches the screen edge": "Leiste einblenden, wenn der Zeiger den Bildschirmrand erreicht",
        "Reveal when the cursor reaches the screen edge": "Einblenden, wenn der Zeiger den Bildschirmrand erreicht",
        "Running...": "Läuft...",
        "Save": "Speichern",
        " • Saved": " • Gespeichert",
        "Saved": "Gespeichert",
        "Saved networks": "Gespeicherte Netzwerke",
        "Scanning face...": "Scanne Gesicht...",
        "Schemes": "Farbschemata",
        "Screen recorder": "Bildschirmaufnahme",
        "Screen Recorder": "Bildschirmaufnahme",
        "Scroll actions": "Scroll-Aktionen",
        "Scroll on the bottom half of the bar to adjust brightness": "Auf der unteren Hälfte der Leiste scrollen, um die Helligkeit anzupassen",
        "Scroll on the top half of the bar to adjust volume": "Auf der oberen Hälfte der Leiste scrollen, um die Lautstärke anzupassen",
        "Scroll over the workspace indicator to switch workspaces": "Über den Arbeitsflächen-Indikator scrollen, um Arbeitsflächen zu wechseln",
        "Searching for devices…": "Suche nach Geräten…",
        "Search settings": "Einstellungen durchsuchen",
        "Secured": "Gesichert",
        "Security": "Sicherheit",
        "Security: %1%2": "Sicherheit: %1%2",
        "Select": "Auswählen",
        "Select a file": "Datei auswählen",
        "Select an image": "Bild auswählen",
        "Select a profile picture": "Profilbild auswählen",
        "Select a wallpaper": "Hintergrundbild auswählen",
        "Selected": "Ausgewählt",
        "Selected candidate: %1 | %2 | %3": "Ausgewählter Kandidat: %1 | %2 | %3",
        "Services": "Dienste",
        "Service tuning": "Dienst-Feinabstimmung",
        "Set it now!": "Jetzt festlegen!",
        "Settings": "Einstellungen",
        "Shell": "Shell",
        "Show a details popout when hovering the status icons": "Details-Ausklappung beim Überfahren der Statussymbole anzeigen",
        "Show all networks (%1)": "Alle Netzwerke anzeigen (%1)",
        "Show a window details popout when hovering": "Fensterdetails beim Überfahren ausklappen",
        "Show date": "Datum anzeigen",
        "Show each monitor's workspaces independently": "Arbeitsflächen jedes Monitors unabhängig anzeigen",
        "Show icon": "Symbol anzeigen",
        "Show icons of open windows on each workspace": "Symbole offener Fenster auf jeder Arbeitsfläche anzeigen",
        "Show in fullscreen": "Im Vollbild anzeigen",
        "Shown": "Angezeigt",
        "Shown in the list": "In der Liste angezeigt",
        "Show notifications expanded by default": "Benachrichtigungen standardmäßig erweitert anzeigen",
        "Show on hover": "Beim Überfahren anzeigen",
        "Show the idle inhibitor card": "Karte für Ruhe-Verhinderung anzeigen",
        "Show the quick toggles card": "Karte für Schnellschalter anzeigen",
        "Show the screen recorder card": "Karte für Bildschirmaufnahme anzeigen",
        "Show the tray menu popout when hovering": "Tray-Menü beim Überfahren ausklappen",
        "Show the utilities panel": "Werkzeug-Panel anzeigen",
        "Show windows": "Fenster anzeigen",
        "Sidebar": "Seitenleiste",
        "Signal": "Signal",
        "Silence notifications": "Benachrichtigungen stummschalten",
        "Size: %1 x %2": "Größe: %1 x %2",
        "Smart colour scheme": "Intelligentes Farbschema",
        "Software": "Software",
        "Source used to fetch synced lyrics": "Quelle für synchronisierten Liedtext",
        "Speakers": "Lautsprecher",
        "Speed": "Geschwindigkeit",
        "Status": "Status",
        "Status icons": "Statussymbole",
        "Storage": "Speicherplatz",
        "System": "System",
        "System information, credits": "Systeminformationen, Danksagungen",
        "System language": "Systemsprache",
        "System stats refresh": "Aktualisierung der Systemstatistiken",
        "System temperatures": "Systemtemperaturen",
        "System tray icons": "System-Tray-Symbole",
        "System updates": "Systemaktualisierungen",
        "Tabs": "Tabs",
        "Tap to select": "Zum Auswählen tippen",
        "Taskbar": "Taskleiste",
        "Temperature": "Temperatur",
        "This folder is empty": "Dieser Ordner ist leer",
        "This page will be available in a future update.": "Diese Seite wird in einem künftigen Update verfügbar sein.",
        "Tile": "Kacheln",
        "Time %1: %2": "Zeit %1: %2",
        "Time before a notification dismisses (ms)": "Zeit, bevor eine Benachrichtigung ausgeblendet wird (ms)",
        "Time & date": "Zeit & Datum",
        "Title display, popout": "Titelanzeige, Ausklappung",
        "Toast events": "Toast-Ereignisse",
        "Toasts": "Toasts",
        "Today": "Heute",
        "Toggle game mode": "Spielmodus umschalten",
        "Toggle the Bluetooth adapter": "Bluetooth-Adapter umschalten",
        "Toggle wireless networking": "WLAN umschalten",
        "Tonal Spot": "Tonal Spot",
        "Total": "Gesamt",
        "Transparency": "Transparenz",
        "Tray": "Tray",
        "Trusted": "Vertraut",
        "Try playing some music!": "Spiele etwas Musik ab!",
        "Try putting some wallpapers in %1": "Lege Hintergrundbilder in %1 ab",
        "Try searching for something else": "Versuche, nach etwas anderem zu suchen",
        "Try switching to a window": "Versuche, zu einem Fenster zu wechseln",
        "Type an expression to calculate": "Ausdruck zum Berechnen eingeben",
        "UI language, weather location, display units": "UI-Sprache, Wetterort, Anzeigeeinheiten",
        "Unavailable": "Nicht verfügbar",
        "Units": "Einheiten",
        "Units for CPU and GPU temperatures": "Einheiten für CPU- und GPU-Temperaturen",
        "Units for weather temperatures": "Einheiten für Wettertemperaturen",
        "Unknown": "Unbekannt",
        "Unknown album": "Unbekanntes Album",
        "Unknown Application": "Unbekannte Anwendung",
        "Unknown artist": "Unbekannter Interpret",
        "Unknown City": "Unbekannte Stadt",
        "Unknown device": "Unbekanntes Gerät",
        "Unknown Device": "Unbekanntes Gerät",
        "Unknown title": "Unbekannter Titel",
        "Unknown track": "Unbekannter Titel",
        "Unlock for Notifications": "Zum Anzeigen der Benachrichtigungen entsperren",
        "Unnamed": "Unbenannt",
        "Unpin": "Lösen",
        "Updates": "Aktualisierungen",
        "Upload": "Hochladen",
        "Upper limit for output volume (%)": "Obergrenze für die Ausgabelautstärke (%)",
        "Usage": "Auslastung",
        "Used": "Belegt",
        "Utilities": "Werkzeuge",
        "Variants": "Varianten",
        "Vibrant": "Lebendig",
        "Vim keybinds": "Vim-Tastenkürzel",
        "Visible icons": "Sichtbare Symbole",
        "Visible indicators": "Sichtbare Indikatoren",
        "Visible toasts": "Sichtbare Toasts",
        "Visualiser bars": "Visualisierungsbalken",
        "Volume": "Lautstärke",
        "Volume (%1)": "Lautstärke (%1)",
        "Volume step": "Lautstärkeschritt",
        "VPN": "VPN",
        "VPN authentication required": "VPN-Authentifizierung erforderlich",
        "VPN changes": "VPN-Änderungen",
        "VPN connected": "VPN verbunden",
        "VPN connection failed": "VPN-Verbindung fehlgeschlagen",
        "VPN disconnected": "VPN getrennt",
        "VPN disconnection failed": "VPN-Trennung fehlgeschlagen",
        "VPN error": "VPN-Fehler",
        "Wake allowed": "Aufwecken erlaubt",
        "Wallpaper disabled": "Hintergrundbild deaktiviert",
        "Wallpaper, fonts, colours": "Hintergrundbild, Schriften, Farben",
        "Wallpaper missing?": "Hintergrundbild fehlt?",
        "Wallpapers": "Hintergrundbilder",
        "Wallpaper & style": "Hintergrundbild & Stil",
        "Weather": "Wetter",
        "Whether notifications appear over fullscreen apps": "Ob Benachrichtigungen über Vollbild-Apps erscheinen",
        "Whether toasts appear over fullscreen apps": "Ob Toasts über Vollbild-Apps erscheinen",
        "Wi-Fi": "WLAN",
        "Wi-Fi disabled": "WLAN deaktiviert",
        "Wi-Fi, ethernet, VPN": "WLAN, Ethernet, VPN",
        "Wi-Fi rescan": "WLAN neu scannen",
        "Windows on special workspaces": "Fenster auf speziellen Arbeitsflächen",
        "Wired connection": "Kabelverbindung",
        "Wireless": "Drahtlos",
        "Workspace: %1 (%2)": "Arbeitsfläche: %1 (%2)",
        "Workspaces": "Arbeitsflächen",
        "WPA passwords are at least 8 characters": "WPA-Passwörter sind mindestens 8 Zeichen lang",
        "WPA/WPA2/WPA3 Personal": "WPA/WPA2/WPA3 Personal",
        "XKB supports only 4 layouts at a time": "XKB unterstützt nur 4 Layouts gleichzeitig",
        "Xwayland: %1": "Xwayland: %1",
        "\"%1\" selected": "„%1“ ausgewählt",
        "Keyboard shortcuts": "Tastaturkürzel",
        "Toggle all panels": "Alle Panels umschalten",
        "Clear notifications": "Benachrichtigungen löschen",
        "Lock": "Sperren",
        "Screenshot": "Bildschirmfoto",
        "Play/Pause": "Wiedergabe/Pause",
        "Next track": "Nächster Titel",
        "Previous track": "Vorheriger Titel",
        "Windows": "Fenster",
        "Close window": "Fenster schließen",
        "Toggle floating": "Schwebend umschalten",
        "Pin window": "Fenster anheften",
        "Focus window": "Fenster fokussieren",
        "Move window": "Fenster verschieben",
        "Drag window (mouse)": "Fenster ziehen (Maus)",
        "Resize window (mouse)": "Fenstergröße ändern (Maus)",
        "Switch to workspace": "Zur Arbeitsfläche wechseln",
        "Move window to workspace": "Fenster auf Arbeitsfläche verschieben",
        "Special workspace": "Spezielle Arbeitsfläche",
        "Music workspace": "Musik-Arbeitsfläche",
        "Communication workspace": "Kommunikations-Arbeitsfläche",
        "Todo workspace": "Todo-Arbeitsfläche",
        "Applications": "Anwendungen",
        "Terminal": "Terminal",
        "Browser": "Browser",
        "Editor": "Editor",
        "Session": "Sitzung",
        "Clipboard": "Zwischenablage",
        "Media & volume": "Medien & Lautstärke",
        "Volume up": "Lauter",
        "Volume down": "Leiser",
        "Mute": "Stummschalten"
    })
}
